site_name: ELEC 360
docs_dir: Notes
site_url: http://uvicnotes.github.io/ELEC-360/
repo_url: https://github.com/UVicNotes/ELEC-360
site_description: Course Notes for ELEC 360 - Control Theory and Systems
site_author: Andrei Taylor
extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://cdn.rawgit.com/UVicNotes/UVicNotes/81099952ba789829fab1840e5d26cb5a2bf62011/helpers/mathjax.js
markdown_extensions:
    - mdx_math
theme: readthedocs
